ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp

patchedDependencies:
  nuxt: patches/nuxt.patch
  '@nuxt/vite-builder': patches/@nuxt__vite-builder.patch
  '@nuxt/content': patches/@nuxt__content.patch
  vue-onigiri: patches/vue-onigiri.patch
