allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  core-js: false
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
  workerd: true
ignoredBuiltDependencies:
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js
  - esbuild
  - sharp
overrides:
  vue-onigiri: file:../vue-onigiri/packages/core/vue-onigiri-0.3.2.tgz
patchedDependencies:
  '@nuxt/nitro-server': patches/@nuxt__nitro-server.patch
  '@nuxt/vite-builder': patches/@nuxt__vite-builder.patch
  nuxt: patches/nuxt.patch
